export const products = [
  { id: 1, name: "Blue T-Shirt", category: "Clothing", price: 150, inStock: true },
  { id: 2, name: "Black Jeans", category: "Clothing", price: 300, inStock: false },
  { id: 3, name: "Red Sneakers", category: "Shoes", price: 500, inStock: true },
  { id: 4, name: "Wireless Mouse", category: "Accessories", price: 250, inStock: true },
  { id: 5, name: "Office Chair", category: "Furniture", price: 1200, inStock: false },
  { id: 6, name: "White Hoodie", category: "Clothing", price: 400, inStock: true },
  { id: 7, name: "Leather Boots", category: "Shoes", price: 850, inStock: false },
  { id: 8, name: "Smartwatch", category: "Accessories", price: 1800, inStock: true },
  { id: 9, name: "Laptop Stand", category: "Furniture", price: 600, inStock: true },
  { id: 10, name: "Bluetooth Headphones", category: "Electronics", price: 1200, inStock: true },
  { id: 11, name: "Graphic Tee", category: "Clothing", price: 220, inStock: true },
  { id: 12, name: "Running Shoes", category: "Shoes", price: 950, inStock: true },
  { id: 13, name: "Sunglasses", category: "Accessories", price: 300, inStock: false },
  { id: 14, name: "Bookshelf", category: "Furniture", price: 1500, inStock: true },
  { id: 15, name: "LED Monitor", category: "Electronics", price: 3200, inStock: false },
  { id: 16, name: "Wireless Keyboard", category: "Accessories", price: 400, inStock: true },
  { id: 17, name: "JavaScript Guide", category: "Books", price: 550, inStock: true },
  { id: 18, name: "Bluetooth Speaker", category: "Electronics", price: 950, inStock: true },
  { id: 19, name: "Ergonomic Desk", category: "Furniture", price: 2500, inStock: false },
  { id: 20, name: "Backpack", category: "Accessories", price: 700, inStock: true },
];